##########################
# Services Configuration #
##########################

environment: testnet # [testnet|mainnet|devnet]
log_level: debug # [debug|info]

external_api:
  endpoints:
    coingecko: "https://api.coingecko.com/api/v3/"
    ens: "https://api.thegraph.com/subgraphs/name/ensdomains/ens"

mainnet:
  bridge:
    config:
      aws:
        s3_bucket: "config.amarok.bridge.connext.network"
      git:
        repo: "CoinHippo-Labs/connext-bridge"
      whitelists: ""

testnet:
  bridge:
    config:
      aws:
        s3_bucket: "config.amarok.bridge.connext.network"
      git:
        repo: "CoinHippo-Labs/connext-bridge"
      whitelists: ""